# Generated by Django 5.2 on 2025-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image_url_user_social_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_auth_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
