# Generated by Django 5.2 on 2025-06-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_social_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
