# Generated by Django 5.2 on 2026-03-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
