# Generated by Django 5.2 on 2026-04-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_runtime_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='heightledger',
            name='engine2_delta_dm',
            field=models.BigIntegerField(default=0),
        ),
    ]
