# Generated by Django 5.2 on 2025-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posture_images/')),
                ('detected_type', models.CharField(choices=[('front', 'Front'), ('side', 'Side')], max_length=10)),
                ('uploaded_type', models.CharField(choices=[('front', 'Front'), ('side', 'Side')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
