# Generated by Django 5.2 on 2025-04-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postureimage',
            options={'verbose_name': 'Posture Image', 'verbose_name_plural': 'Posture Images'},
        ),
        migrations.AddField(
            model_name='postureimage',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postureimage',
            name='pose_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='postureimage',
            name='posture_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postureimage',
            name='recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
