# Generated by Django 5.2 on 2025-04-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0003_alter_postureimage_options_postureimage_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postureimage',
            name='height_loss_inches',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
