# Generated by Django 5.2 on 2025-12-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0005_posturereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='posturereport',
            name='t_pose_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
