# Generated by Django 5.2 on 2026-01-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0006_posturereport_t_pose_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='posturereport',
            name='back_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posturereport',
            name='front_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posturereport',
            name='side_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
