# Generated by Django 5.2 on 2026-01-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0007_posturereport_back_data_posturereport_front_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posturereport',
            name='raw_request_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
