# Generated by Django 5.2 on 2026-02-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0008_posturereport_raw_request_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='posturereport',
            name='max_height_gain_inches',
            field=models.TextField(blank=True, null=True),
        ),
    ]
