# Generated by Django 5.2 on 2025-04-25 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_head_posture_question', models.CharField(blank=True, max_length=255, null=True)),
                ('forward_head_posture_options', models.CharField(blank=True, max_length=255, null=True)),
                ('forward_head_posture_answer', models.TextField(blank=True, null=True)),
                ('gap_between_your_lower_back_question', models.CharField(blank=True, max_length=255, null=True)),
                ('gap_between_your_lower_back_options', models.CharField(blank=True, max_length=255, null=True)),
                ('gap_between_your_lower_back_answer', models.TextField(blank=True, null=True)),
                ('tightness_or_discomfort_question', models.CharField(blank=True, max_length=255, null=True)),
                ('tightness_or_discomfort_options', models.CharField(blank=True, max_length=255, null=True)),
                ('tightness_or_discomfort_answer', models.TextField(blank=True, null=True)),
                ('slouch_when_standing_or_sitting_question', models.CharField(blank=True, max_length=255, null=True)),
                ('slouch_when_standing_or_sitting_options', models.CharField(blank=True, max_length=255, null=True)),
                ('slouch_when_standing_or_sitting_answer', models.TextField(blank=True, null=True)),
                ('feel_noticeably_shorter_end_of_day_compare_to_morning_question', models.CharField(blank=True, max_length=255, null=True)),
                ('feel_noticeably_shorter_end_of_day_compare_to_morning_options', models.CharField(blank=True, max_length=100, null=True)),
                ('feel_noticeably_shorter_end_of_day_compare_to_morning_answer', models.TextField(blank=True, null=True)),
                ('perfectly_aligned_and_decompressed_question', models.CharField(blank=True, max_length=255, null=True)),
                ('perfectly_aligned_and_decompressed_options', models.CharField(blank=True, max_length=100, null=True)),
                ('perfectly_aligned_and_decompressed_answer', models.TextField(blank=True, null=True)),
                ('flexible_in_your_hamstrings_and_hips_question', models.CharField(blank=True, max_length=255, null=True)),
                ('flexible_in_your_hamstrings_and_hips_options', models.CharField(blank=True, max_length=100, null=True)),
                ('flexible_in_your_hamstrings_and_hips_answer', models.TextField(blank=True, null=True)),
                ('active_your_core_during_daily_task_question', models.CharField(blank=True, max_length=255, null=True)),
                ('active_your_core_during_daily_task_options', models.CharField(blank=True, max_length=100, null=True)),
                ('active_your_core_during_daily_task_answer', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posture_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
