# Generated by Django 5.2 on 2025-05-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturequestion',
            name='active_your_core_during_daily_task_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='active_your_core_during_daily_task_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='feel_noticeably_shorter_end_of_day_compare_to_morning_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='feel_noticeably_shorter_end_of_day_compare_to_morning_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='flexible_in_your_hamstrings_and_hips_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='flexible_in_your_hamstrings_and_hips_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='forward_head_posture_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='forward_head_posture_question',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='gap_between_your_lower_back_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='gap_between_your_lower_back_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='perfectly_aligned_and_decompressed_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='perfectly_aligned_and_decompressed_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='slouch_when_standing_or_sitting_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='slouch_when_standing_or_sitting_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='tightness_or_discomfort_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posturequestion',
            name='tightness_or_discomfort_question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
