# Generated by Django 5.2 on 2025-06-06 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosturalOptimizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('max_height_gain_inches', models.FloatField()),
                ('note', models.TextField()),
                ('spinal_compression', models.PositiveSmallIntegerField()),
                ('posture_collapse', models.PositiveSmallIntegerField()),
                ('pelvic_tilt_back', models.PositiveSmallIntegerField()),
                ('leg_hamstring', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosturalRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='posture_analysis.userposturaloptimizationdata')),
            ],
        ),
    ]
