# Generated by Django 5.2 on 2025-10-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpackage',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of package features'),
        ),
        migrations.AddField(
            model_name='paymentpackage',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Mark this package as free'),
        ),
        migrations.AlterField(
            model_name='paymentpackage',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
