# Generated by Django 5.2 on 2025-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='question_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
