# Generated by Django 5.2 on 2025-04-18 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('serving_description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('spine_support', 'Spine Support & Disc Lubrication Foods'), ('posture_muscle', 'Posture Muscle Repair & Fuel Foods'), ('growth_boost', 'Growth Boosting Foods'), ('sleep', 'Sleep'), ('sunlight', 'Sunlight'), ('meditation', 'Meditation'), ('hydration', 'Hydration')], default='spine_support', max_length=50)),
                ('age_group', models.CharField(choices=[('14-20', '14-20'), ('21+', '21+')], default='21+', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='WellnessSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wellness_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness_tracker.wellnessitem')),
            ],
        ),
    ]
