# Generated by Django 5.2 on 2025-04-21 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessitem',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/posture_images/'),
            preserve_default=False,
        ),
    ]
