# Generated by Django 5.2 on 2025-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_tracker', '0002_wellnessitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessitem',
            name='image',
            field=models.ImageField(upload_to='uploads/wellness_items/'),
        ),
    ]
