# Generated by Django 5.2 on 2025-04-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_tracker', '0003_alter_wellnessitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessitem',
            name='age_group',
            field=models.CharField(choices=[('13-17', '13-17'), ('13-20', '13-20'), ('18-20', '18-20'), ('21+', '21+')], default='21+', max_length=5),
        ),
        migrations.AlterField(
            model_name='wellnessitem',
            name='image',
            field=models.ImageField(upload_to='wellness_items/'),
        ),
    ]
