# Generated by Django 5.2 on 2025-04-22 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('serving_description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('height_max_essentials', 'Core 6 - HeightMax Essentials'), ('extras_to_pick', 'Extras To Pick From')], default='height_max_essentials', max_length=50)),
                ('age_group', models.CharField(choices=[('14-17', '14-17'), ('18-20', '18-20'), ('21-29', '21-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('50-59', '50-59'), ('60+', '60+')], default='21+', max_length=5)),
                ('image', models.ImageField(upload_to='exercise_items/')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Exercise_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciseitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
