# Generated by Django 5.2 on 2025-04-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseitem',
            name='age_group',
            field=models.CharField(choices=[('13-17', '13-17'), ('18-20', '18-20'), ('21-29', '21-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('50-59', '50-59'), ('60+', '60+')], default='13-17', max_length=5),
        ),
        migrations.AlterField(
            model_name='exerciseitem',
            name='category',
            field=models.CharField(choices=[('core_six_height_max_essentials', 'Core 6 - HeightMax Essentials'), ('core_four_height_max_posture', 'Core 4 - HeightMax Posture'), ('core_two_height_max_hgh', 'Core 2 - HeightMax HGH'), ('extras_to_pick', 'Extras To Pick From')], default='height_max_essentials', max_length=50),
        ),
    ]
