# Generated by Django 5.2 on 2025-05-15 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('min_age', models.PositiveSmallIntegerField()),
                ('max_age', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('min_age',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('NUT', 'Nutrition'), ('LIFE', 'Lifestyle')], max_length=4)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='nutration.agegroup')),
            ],
            options={
                'ordering': ('age_group__min_age', 'type', 'name'),
                'unique_together': {('name', 'age_group')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('score', models.PositiveSmallIntegerField(help_text='Importance or target frequency', validators=[django.core.validators.MinValueValidator(1)])),
                ('serving_size', models.CharField(blank=True, max_length=120)),
                ('details', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutration.module')),
            ],
            options={
                'ordering': ('-score', 'name'),
            },
        ),
    ]
