# Generated by Django 5.2 on 2025-05-15 12:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, upload_to='foods/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ModuleFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Importance / target frequency', validators=[django.core.validators.MinValueValidator(1)])),
                ('serving_size', models.CharField(blank=True, max_length=120)),
                ('details', models.TextField(blank=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_foods', to='nutration.food')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_foods', to='nutration.module')),
            ],
            options={
                'ordering': ('-score', 'food__name'),
                'unique_together': {('module', 'food')},
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
