# Generated by Django 5.2 on 2025-05-15 12:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutration', '0002_food_modulefood_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('default_duration', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='activities/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='modulefood',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='ModuleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('recommendation', models.CharField(blank=True, max_length=120)),
                ('details', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activities', to='nutration.activity')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activities', to='nutration.module')),
            ],
            options={
                'ordering': ('-score', 'activity__name'),
                'unique_together': {('module', 'activity')},
            },
        ),
    ]
