# Generated by Django 5.2 on 2025-05-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutration', '0003_activity_alter_modulefood_score_moduleactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
