# Generated by Django 5.2 on 2025-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutration', '0005_nutrasession_nutraentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutraentry',
            name='servings',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
