# Generated by Django 5.2 on 2025-06-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutration', '0006_alter_nutraentry_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='short_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='food',
            name='short_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
