# Generated by Django 5.2 on 2025-06-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutration', '0007_activity_short_name_food_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='short_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='food',
            name='short_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
