# Generated by Django 5.2 on 2025-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutration', '0008_alter_activity_short_name_alter_food_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleactivity',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='module_activities/audio/'),
        ),
        migrations.AddField(
            model_name='moduleactivity',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='module_activities/video/'),
        ),
    ]
