# Generated by Django 5.2 on 2026-01-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutration', '0009_moduleactivity_audio_moduleactivity_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='action_btn',
            field=models.CharField(blank=True, help_text='CTA text (e.g. Start, Explore, Track)', max_length=80),
        ),
        migrations.AddField(
            model_name='module',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/backgrounds/'),
        ),
        migrations.AddField(
            model_name='module',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/icons/'),
        ),
        migrations.AddField(
            model_name='module',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short display name (e.g. Protein Boost)', max_length=80),
        ),
        migrations.AddField(
            model_name='module',
            name='tag_line',
            field=models.CharField(blank=True, help_text='Short motivational line', max_length=160),
        ),
    ]
