# Generated by Django 5.2 on 2026-05-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutration', '0013_module_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('age_group__min_age', 'type', 'sort_order', 'name')},
        ),
    ]
