# Generated by Django 5.2 on 2025-05-28 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticHeightEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_height_cm', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genetic_estimate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeightGrowthProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_age', models.IntegerField()),
                ('current_height_cm', models.FloatField()),
                ('age_range', models.CharField(max_length=20)),
                ('annual_growth_percent', models.FloatField()),
                ('estimated_annual_gain_cm', models.FloatField()),
                ('estimated_daily_gain_cm', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genetic_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_projections', to='height_analysis.geneticheightestimate')),
            ],
        ),
    ]
