# Generated by Django 5.2 on 2025-08-20 12:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('min_age', models.PositiveSmallIntegerField()),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['min_age'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('posture', 'Posture'), ('environment', 'Environment'), ('hgh', 'HGH / Sprint'), ('general', 'General')], default='general', max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exercises/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('ess', 'Essentials'), ('pos', 'Posture'), ('hgh', 'HGH')], default='ess', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('age_bracket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_variants', to='workouts.agebracket')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='workouts.routinetemplate')),
            ],
            options={
                'ordering': ['template__name', 'age_bracket__min_age'],
                'unique_together': {('template', 'age_bracket', 'track')},
            },
        ),
        migrations.CreateModel(
            name='UserRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_type', models.CharField(choices=[('posture', 'Posture Routine'), ('hgh', 'HGH Routine')], default='POSTURE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scan_score', models.JSONField(default=dict)),
                ('optimization_breakdown', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Routine',
                'verbose_name_plural': 'User Routines',
            },
        ),
        migrations.CreateModel(
            name='UserRoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('core', 'Core'), ('rec', 'Recommended'), ('beast', 'Beast mode')], max_length=6)),
                ('order', models.PositiveSmallIntegerField()),
                ('sets', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('qty_min', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('qty_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('reps', 'Reps'), ('secs', 'Seconds')], default='reps', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.userroutine')),
            ],
            options={
                'ordering': ['routine', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VariantExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('sets', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('reps', 'Reps'), ('secs', 'Seconds')], default='reps', max_length=8)),
                ('tier', models.CharField(choices=[('core', 'Core'), ('rec', 'Recommended'), ('beast', 'Beast mode')], default='core', max_length=5)),
                ('type', models.CharField(choices=[('main', 'Main'), ('spinal_compression', 'Spinal Compression'), ('postural_collapse', 'Postural Collapse'), ('pelvic_tilt_back', 'Pelvic Tilt & Back'), ('leg_hamstring', 'Leg & Hamstring')], default='main', max_length=25)),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.exercise')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='workouts.routinevariant')),
            ],
            options={
                'ordering': ['variant', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('user_routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='workouts.userroutine')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('sets_done', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps_done', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_s', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.exercise')),
                ('user_routine_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.userroutineexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='userroutine',
            index=models.Index(fields=['user', 'routine_type', 'is_active'], name='workouts_us_user_id_4dc7ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='userroutine',
            constraint=models.UniqueConstraint(fields=('user', 'routine_type', 'is_active'), name='unique_active_routine_per_type'),
        ),
        migrations.AlterUniqueTogether(
            name='userroutineexercise',
            unique_together={('routine', 'exercise')},
        ),
        migrations.AlterUniqueTogether(
            name='variantexercise',
            unique_together={('variant', 'exercise')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutsession',
            unique_together={('user', 'user_routine', 'date')},
        ),
    ]
