# Generated by Django 5.2 on 2026-01-01 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroutineexercise',
            name='variant_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workouts.variantexercise'),
        ),
        migrations.AddField(
            model_name='variantexercise',
            name='image_female',
            field=models.ImageField(blank=True, null=True, upload_to='variant_exercises/female/'),
        ),
        migrations.AddField(
            model_name='variantexercise',
            name='image_male',
            field=models.ImageField(blank=True, null=True, upload_to='variant_exercises/male/'),
        ),
    ]
