# Generated by Django 5.2 on 2025-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('complete_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_level_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('current_height_foot', models.IntegerField(blank=True, null=True)),
                ('current_height_inch', models.IntegerField(blank=True, null=True)),
                ('current_height_cm', models.IntegerField(blank=True, null=True)),
                ('current_height_type', models.CharField(blank=True, max_length=20, null=True)),
                ('ideal_height_foot', models.IntegerField(blank=True, null=True)),
                ('ideal_height_inch', models.IntegerField(blank=True, null=True)),
                ('ideal_height_cm', models.IntegerField(blank=True, null=True)),
                ('ideal_height_type', models.CharField(blank=True, max_length=20, null=True)),
                ('father_height_foot', models.IntegerField(blank=True, null=True)),
                ('father_height_inch', models.IntegerField(blank=True, null=True)),
                ('father_height_cm', models.IntegerField(blank=True, null=True)),
                ('father_height_type', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_height_foot', models.IntegerField(blank=True, null=True)),
                ('mother_height_inch', models.IntegerField(blank=True, null=True)),
                ('mother_height_cm', models.IntegerField(blank=True, null=True)),
                ('mother_height_type', models.CharField(blank=True, max_length=20, null=True)),
                ('activity_level_question', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_level_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_level_all_option', models.TextField(blank=True, null=True)),
                ('sitting_hours_question', models.CharField(blank=True, max_length=255, null=True)),
                ('sitting_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('posture_and_flexibility_question_one', models.CharField(blank=True, max_length=255, null=True)),
                ('posture_and_flexibility_answer_one', models.CharField(blank=True, max_length=255, null=True)),
                ('posture_and_flexibility_question_one_all_option', models.TextField(blank=True, null=True)),
                ('posture_and_flexibility_question_two', models.CharField(blank=True, max_length=255, null=True)),
                ('posture_and_flexibility_answer_two', models.CharField(blank=True, max_length=255, null=True)),
                ('posture_and_flexibility_question_two_all_option', models.TextField(blank=True, null=True)),
                ('posture_and_flexibility_question_three', models.CharField(blank=True, max_length=255, null=True)),
                ('posture_and_flexibility_answer_three', models.CharField(blank=True, max_length=255, null=True)),
                ('posture_and_flexibility_question_three_all_option', models.TextField(blank=True, null=True)),
                ('sleep_quality_and_position_question_one', models.CharField(blank=True, max_length=255, null=True)),
                ('sleep_quality_and_position_answer_one', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_quality_and_position_question_two', models.CharField(blank=True, max_length=255, null=True)),
                ('sleep_quality_and_position_answer_two', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_quality_and_position_question_two_all_option', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
