# Generated by Django 5.2 on 2025-05-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_weight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shoe_size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
