# Generated by Django 5.2 on 2025-05-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_current_weight_userprofile_shoe_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_weight_lbs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shoe_size_eu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
