# Generated by Django 5.2 on 2025-05-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_current_weight_lbs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sitting_hours',
            new_name='discomfort_in_body_during_movement_answer',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discomfort_in_body_during_movement_options',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discomfort_in_body_during_movement_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_goal_with_heightmax_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_goal_with_heightmax_options',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_goal_with_heightmax_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sitting_hours_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sitting_hours_options',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sleep_hours_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sleep_hours_options',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sleep_hours_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='touch_toes_wt_bending_knees_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='touch_toes_wt_bending_knees_options',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='touch_toes_wt_bending_knees_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
