# Generated by Django 5.2 on 2025-06-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_profiletype_activity_level_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
