# Generated by Django 5.2 on 2025-07-01 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_packages', '0001_initial'),
        ('user_profile', '0008_userprofile_last_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paymentpackage', to='payment_packages.paymentpackage'),
            preserve_default=False,
        ),
    ]
