# Generated by Django 5.2 on 2026-01-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_payment_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='g_p_facial_armpit_hair',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='g_p_height_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='g_p_looks',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='g_p_shoe_pant_growth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='g_p_voice_stage',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
