# Generated by Django 5.2 on 2026-01-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_userprofile_g_p_facial_armpit_hair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='g_p_facial_armpit_hair',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='g_p_height_change',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='g_p_looks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='g_p_shoe_pant_growth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='g_p_voice_stage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
